//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tercera_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCiudad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCiudad()
        {
            this.tbEmpleados = new HashSet<tbEmpleados>();
        }
    
        public int Ciu_Id { get; set; }
        public string Ciu_Descripcion { get; set; }
        public Nullable<int> Ciu_Id_Dpto { get; set; }
        public Nullable<int> Ciu_UsuCrea { get; set; }
        public Nullable<System.DateTime> Ciu_FechaCrea { get; set; }
        public Nullable<int> Ciu_UsuModifica { get; set; }
        public Nullable<System.DateTime> Ciu_FechaMidifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
        public virtual tbDepartamento tbDepartamento { get; set; }
    }
}
