//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tercera_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDepartamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbDepartamento()
        {
            this.tbCiudad = new HashSet<tbCiudad>();
        }
    
        public int Dept_Id { get; set; }
        public string Dept_Descripcion { get; set; }
        public Nullable<int> Dept_UsuCrea { get; set; }
        public Nullable<System.DateTime> Dept_FechaCrea { get; set; }
        public Nullable<int> Dept_UsuModifica { get; set; }
        public Nullable<System.DateTime> Dept_FechaMidifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCiudad> tbCiudad { get; set; }
    }
}
