//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tercera_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEmpleados
    {
        public int Emp_Id { get; set; }
        public string Emp_Nombre { get; set; }
        public string Emp_Apellido { get; set; }
        public string Emp_Sexo { get; set; }
        public Nullable<int> Emp_Edad { get; set; }
        public Nullable<int> Emp_Ciudad { get; set; }
        public Nullable<int> Emp_UsuCrea { get; set; }
        public Nullable<System.DateTime> Emp_FechaCrea { get; set; }
        public Nullable<int> Emp_UsuModifica { get; set; }
        public Nullable<System.DateTime> Emp_FechaMidifica { get; set; }
    
        public virtual tbCiudad tbCiudad { get; set; }
    }
}
